[project]
name = "esp32"
version = "0.1.0"
description = "Servidor para nossa ESP32"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "paho-mqtt>=2.1.0",
    "websockets>=15.0.1",
]
